name: "Brownian Bridge Process - pred clean speech"
backbone: 
  name: "ncsnpp"
  scale_by_sigma: False
sde:
  name: "bb"
lr: 0.00002
loss: "mse_x0"
pred_type: "x0"
t_eps: 0.03
ema_decay: 0.999
epochs: 120
validation:
  val_interval: 3
  num_eval_files: 20
inference:
  name: "diffusion"
  sampler_type: "pc"
  predictor: "reverse_diffusion"
  corrector: "ald"
  N: 30
  corrector_steps: 1
  snr: 0.5
dataset:
  base_dir: "../data/voicebank_demand"
  format: "default"
  batch_size: 8
  n_fft: 510
  hop_length: 128
  num_frames: 256
  window: "hann"
  num_workers: 4
  spec_factor: 0.15
  spec_abs_exponent: 0.5
  normalize: "noisy"
  transform_type: "exponent"
