name: "OUVE - pred clean speech"
backbone: "ncsnpp"
sde:
  name: "ouve"
  sigma_max: 0.5
  sigma_min: 0.05
  theta: 1.5
lr: 0.00002
loss: "mse_x0"
pred_type: "x0"
ema_decay: 0.999
epochs: 120
validation:
  val_interval: 3
  num_eval_files: 20
inference:
  name: "diffusion"
  sampler_type: "pc"
  predictor: "reverse_diffusion"
  corrector: "ald"
  N: 30
  corrector_steps: 1
  snr: 0.5
dataset:
  base_dir: "../data/voicebank_demand"
  format: "default"
  batch_size: 8
  n_fft: 510
  hop_length: 128
  num_frames: 256
  window: "hann"
  num_workers: 4
  spec_factor: 0.15
  spec_abs_exponent: 0.5
  normalize: "noisy"
  transform_type: "exponent"
